# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shortcut_client_py
from shortcut_client_py.models.basic_workspace_info import BasicWorkspaceInfo  # noqa: E501
from shortcut_client_py.rest import ApiException


class TestBasicWorkspaceInfo(unittest.TestCase):
    """BasicWorkspaceInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasicWorkspaceInfo(self):
        """Test BasicWorkspaceInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = shortcut_client_py.models.basic_workspace_info.BasicWorkspaceInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
