# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shortcut_client_py
from shortcut_client_py.api.default_api import DefaultApi  # noqa: E501
from shortcut_client_py.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_category(self):
        """Test case for create_category

        Create Category  # noqa: E501
        """
        pass

    def test_create_entity_template(self):
        """Test case for create_entity_template

        Create Entity Template  # noqa: E501
        """
        pass

    def test_create_epic(self):
        """Test case for create_epic

        Create Epic  # noqa: E501
        """
        pass

    def test_create_epic_comment(self):
        """Test case for create_epic_comment

        Create Epic Comment  # noqa: E501
        """
        pass

    def test_create_epic_comment_comment(self):
        """Test case for create_epic_comment_comment

        Create Epic Comment Comment  # noqa: E501
        """
        pass

    def test_create_group(self):
        """Test case for create_group

        Create Group  # noqa: E501
        """
        pass

    def test_create_iteration(self):
        """Test case for create_iteration

        Create Iteration  # noqa: E501
        """
        pass

    def test_create_label(self):
        """Test case for create_label

        Create Label  # noqa: E501
        """
        pass

    def test_create_linked_file(self):
        """Test case for create_linked_file

        Create Linked File  # noqa: E501
        """
        pass

    def test_create_milestone(self):
        """Test case for create_milestone

        Create Milestone  # noqa: E501
        """
        pass

    def test_create_multiple_stories(self):
        """Test case for create_multiple_stories

        Create Multiple Stories  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create Project  # noqa: E501
        """
        pass

    def test_create_story(self):
        """Test case for create_story

        Create Story  # noqa: E501
        """
        pass

    def test_create_story_comment(self):
        """Test case for create_story_comment

        Create Story Comment  # noqa: E501
        """
        pass

    def test_create_story_link(self):
        """Test case for create_story_link

        Create Story Link  # noqa: E501
        """
        pass

    def test_create_story_reaction(self):
        """Test case for create_story_reaction

        Create Story Reaction  # noqa: E501
        """
        pass

    def test_create_task(self):
        """Test case for create_task

        Create Task  # noqa: E501
        """
        pass

    def test_delete_category(self):
        """Test case for delete_category

        Delete Category  # noqa: E501
        """
        pass

    def test_delete_entity_template(self):
        """Test case for delete_entity_template

        Delete Entity Template  # noqa: E501
        """
        pass

    def test_delete_epic(self):
        """Test case for delete_epic

        Delete Epic  # noqa: E501
        """
        pass

    def test_delete_epic_comment(self):
        """Test case for delete_epic_comment

        Delete Epic Comment  # noqa: E501
        """
        pass

    def test_delete_file(self):
        """Test case for delete_file

        Delete File  # noqa: E501
        """
        pass

    def test_delete_iteration(self):
        """Test case for delete_iteration

        Delete Iteration  # noqa: E501
        """
        pass

    def test_delete_label(self):
        """Test case for delete_label

        Delete Label  # noqa: E501
        """
        pass

    def test_delete_linked_file(self):
        """Test case for delete_linked_file

        Delete Linked File  # noqa: E501
        """
        pass

    def test_delete_milestone(self):
        """Test case for delete_milestone

        Delete Milestone  # noqa: E501
        """
        pass

    def test_delete_multiple_stories(self):
        """Test case for delete_multiple_stories

        Delete Multiple Stories  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete Project  # noqa: E501
        """
        pass

    def test_delete_story(self):
        """Test case for delete_story

        Delete Story  # noqa: E501
        """
        pass

    def test_delete_story_comment(self):
        """Test case for delete_story_comment

        Delete Story Comment  # noqa: E501
        """
        pass

    def test_delete_story_link(self):
        """Test case for delete_story_link

        Delete Story Link  # noqa: E501
        """
        pass

    def test_delete_story_reaction(self):
        """Test case for delete_story_reaction

        Delete Story Reaction  # noqa: E501
        """
        pass

    def test_delete_task(self):
        """Test case for delete_task

        Delete Task  # noqa: E501
        """
        pass

    def test_disable_groups(self):
        """Test case for disable_groups

        Disable Groups  # noqa: E501
        """
        pass

    def test_disable_iterations(self):
        """Test case for disable_iterations

        Disable Iterations  # noqa: E501
        """
        pass

    def test_disable_story_templates(self):
        """Test case for disable_story_templates

        Disable Story Templates  # noqa: E501
        """
        pass

    def test_enable_groups(self):
        """Test case for enable_groups

        Enable Groups  # noqa: E501
        """
        pass

    def test_enable_iterations(self):
        """Test case for enable_iterations

        Enable Iterations  # noqa: E501
        """
        pass

    def test_enable_story_templates(self):
        """Test case for enable_story_templates

        Enable Story Templates  # noqa: E501
        """
        pass

    def test_get_category(self):
        """Test case for get_category

        Get Category  # noqa: E501
        """
        pass

    def test_get_current_member_info(self):
        """Test case for get_current_member_info

        Get Current Member Info  # noqa: E501
        """
        pass

    def test_get_entity_template(self):
        """Test case for get_entity_template

        Get Entity Template  # noqa: E501
        """
        pass

    def test_get_epic(self):
        """Test case for get_epic

        Get Epic  # noqa: E501
        """
        pass

    def test_get_epic_comment(self):
        """Test case for get_epic_comment

        Get Epic Comment  # noqa: E501
        """
        pass

    def test_get_epic_workflow(self):
        """Test case for get_epic_workflow

        Get Epic Workflow  # noqa: E501
        """
        pass

    def test_get_external_link_stories(self):
        """Test case for get_external_link_stories

        Get External Link Stories  # noqa: E501
        """
        pass

    def test_get_file(self):
        """Test case for get_file

        Get File  # noqa: E501
        """
        pass

    def test_get_group(self):
        """Test case for get_group

        Get Group  # noqa: E501
        """
        pass

    def test_get_iteration(self):
        """Test case for get_iteration

        Get Iteration  # noqa: E501
        """
        pass

    def test_get_label(self):
        """Test case for get_label

        Get Label  # noqa: E501
        """
        pass

    def test_get_linked_file(self):
        """Test case for get_linked_file

        Get Linked File  # noqa: E501
        """
        pass

    def test_get_member(self):
        """Test case for get_member

        Get Member  # noqa: E501
        """
        pass

    def test_get_milestone(self):
        """Test case for get_milestone

        Get Milestone  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Get Project  # noqa: E501
        """
        pass

    def test_get_repository(self):
        """Test case for get_repository

        Get Repository  # noqa: E501
        """
        pass

    def test_get_story(self):
        """Test case for get_story

        Get Story  # noqa: E501
        """
        pass

    def test_get_story_comment(self):
        """Test case for get_story_comment

        Get Story Comment  # noqa: E501
        """
        pass

    def test_get_story_link(self):
        """Test case for get_story_link

        Get Story Link  # noqa: E501
        """
        pass

    def test_get_task(self):
        """Test case for get_task

        Get Task  # noqa: E501
        """
        pass

    def test_get_workflow(self):
        """Test case for get_workflow

        Get Workflow  # noqa: E501
        """
        pass

    def test_list_categories(self):
        """Test case for list_categories

        List Categories  # noqa: E501
        """
        pass

    def test_list_category_milestones(self):
        """Test case for list_category_milestones

        List Category Milestones  # noqa: E501
        """
        pass

    def test_list_entity_templates(self):
        """Test case for list_entity_templates

        List Entity Templates  # noqa: E501
        """
        pass

    def test_list_epic_comments(self):
        """Test case for list_epic_comments

        List Epic Comments  # noqa: E501
        """
        pass

    def test_list_epic_stories(self):
        """Test case for list_epic_stories

        List Epic Stories  # noqa: E501
        """
        pass

    def test_list_epics(self):
        """Test case for list_epics

        List Epics  # noqa: E501
        """
        pass

    def test_list_files(self):
        """Test case for list_files

        List Files  # noqa: E501
        """
        pass

    def test_list_group_stories(self):
        """Test case for list_group_stories

        List Group Stories  # noqa: E501
        """
        pass

    def test_list_groups(self):
        """Test case for list_groups

        List Groups  # noqa: E501
        """
        pass

    def test_list_iteration_stories(self):
        """Test case for list_iteration_stories

        List Iteration Stories  # noqa: E501
        """
        pass

    def test_list_iterations(self):
        """Test case for list_iterations

        List Iterations  # noqa: E501
        """
        pass

    def test_list_label_epics(self):
        """Test case for list_label_epics

        List Label Epics  # noqa: E501
        """
        pass

    def test_list_label_stories(self):
        """Test case for list_label_stories

        List Label Stories  # noqa: E501
        """
        pass

    def test_list_labels(self):
        """Test case for list_labels

        List Labels  # noqa: E501
        """
        pass

    def test_list_linked_files(self):
        """Test case for list_linked_files

        List Linked Files  # noqa: E501
        """
        pass

    def test_list_members(self):
        """Test case for list_members

        List Members  # noqa: E501
        """
        pass

    def test_list_milestone_epics(self):
        """Test case for list_milestone_epics

        List Milestone Epics  # noqa: E501
        """
        pass

    def test_list_milestones(self):
        """Test case for list_milestones

        List Milestones  # noqa: E501
        """
        pass

    def test_list_projects(self):
        """Test case for list_projects

        List Projects  # noqa: E501
        """
        pass

    def test_list_repositories(self):
        """Test case for list_repositories

        List Repositories  # noqa: E501
        """
        pass

    def test_list_stories(self):
        """Test case for list_stories

        List Stories  # noqa: E501
        """
        pass

    def test_list_workflows(self):
        """Test case for list_workflows

        List Workflows  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        Search  # noqa: E501
        """
        pass

    def test_search_epics(self):
        """Test case for search_epics

        Search Epics  # noqa: E501
        """
        pass

    def test_search_stories(self):
        """Test case for search_stories

        Search Stories  # noqa: E501
        """
        pass

    def test_search_stories_old(self):
        """Test case for search_stories_old

        Search Stories (Old)  # noqa: E501
        """
        pass

    def test_story_history(self):
        """Test case for story_history

        Story History  # noqa: E501
        """
        pass

    def test_unlink_productboard_from_epic(self):
        """Test case for unlink_productboard_from_epic

        Unlink Productboard from Epic  # noqa: E501
        """
        pass

    def test_update_category(self):
        """Test case for update_category

        Update Category  # noqa: E501
        """
        pass

    def test_update_entity_template(self):
        """Test case for update_entity_template

        Update Entity Template  # noqa: E501
        """
        pass

    def test_update_epic(self):
        """Test case for update_epic

        Update Epic  # noqa: E501
        """
        pass

    def test_update_epic_comment(self):
        """Test case for update_epic_comment

        Update Epic Comment  # noqa: E501
        """
        pass

    def test_update_file(self):
        """Test case for update_file

        Update File  # noqa: E501
        """
        pass

    def test_update_group(self):
        """Test case for update_group

        Update Group  # noqa: E501
        """
        pass

    def test_update_iteration(self):
        """Test case for update_iteration

        Update Iteration  # noqa: E501
        """
        pass

    def test_update_label(self):
        """Test case for update_label

        Update Label  # noqa: E501
        """
        pass

    def test_update_linked_file(self):
        """Test case for update_linked_file

        Update Linked File  # noqa: E501
        """
        pass

    def test_update_milestone(self):
        """Test case for update_milestone

        Update Milestone  # noqa: E501
        """
        pass

    def test_update_multiple_stories(self):
        """Test case for update_multiple_stories

        Update Multiple Stories  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update Project  # noqa: E501
        """
        pass

    def test_update_story(self):
        """Test case for update_story

        Update Story  # noqa: E501
        """
        pass

    def test_update_story_comment(self):
        """Test case for update_story_comment

        Update Story Comment  # noqa: E501
        """
        pass

    def test_update_story_link(self):
        """Test case for update_story_link

        Update Story Link  # noqa: E501
        """
        pass

    def test_update_task(self):
        """Test case for update_task

        Update Task  # noqa: E501
        """
        pass

    def test_upload_files(self):
        """Test case for upload_files

        Upload Files  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
