# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shortcut_client_py
from shortcut_client_py.models.uploaded_file import UploadedFile  # noqa: E501
from shortcut_client_py.rest import ApiException


class TestUploadedFile(unittest.TestCase):
    """UploadedFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUploadedFile(self):
        """Test UploadedFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = shortcut_client_py.models.uploaded_file.UploadedFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
