# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shortcut_client_py
from shortcut_client_py.models.epic_state import EpicState  # noqa: E501
from shortcut_client_py.rest import ApiException


class TestEpicState(unittest.TestCase):
    """EpicState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpicState(self):
        """Test EpicState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = shortcut_client_py.models.epic_state.EpicState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
