# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateTask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'complete': 'bool',
        'owner_ids': 'list[str]',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'external_id': 'str'
    }

    attribute_map = {
        'description': 'description',
        'complete': 'complete',
        'owner_ids': 'owner_ids',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'external_id': 'external_id'
    }

    def __init__(self, description=None, complete=None, owner_ids=None, created_at=None, updated_at=None, external_id=None):  # noqa: E501
        """CreateTask - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._complete = None
        self._owner_ids = None
        self._created_at = None
        self._updated_at = None
        self._external_id = None
        self.discriminator = None
        self.description = description
        if complete is not None:
            self.complete = complete
        if owner_ids is not None:
            self.owner_ids = owner_ids
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if external_id is not None:
            self.external_id = external_id

    @property
    def description(self):
        """Gets the description of this CreateTask.  # noqa: E501

        The Task description.  # noqa: E501

        :return: The description of this CreateTask.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateTask.

        The Task description.  # noqa: E501

        :param description: The description of this CreateTask.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def complete(self):
        """Gets the complete of this CreateTask.  # noqa: E501

        True/false boolean indicating whether the Task is completed. Defaults to false.  # noqa: E501

        :return: The complete of this CreateTask.  # noqa: E501
        :rtype: bool
        """
        return self._complete

    @complete.setter
    def complete(self, complete):
        """Sets the complete of this CreateTask.

        True/false boolean indicating whether the Task is completed. Defaults to false.  # noqa: E501

        :param complete: The complete of this CreateTask.  # noqa: E501
        :type: bool
        """

        self._complete = complete

    @property
    def owner_ids(self):
        """Gets the owner_ids of this CreateTask.  # noqa: E501

        An array of UUIDs for any members you want to add as Owners on this new Task.  # noqa: E501

        :return: The owner_ids of this CreateTask.  # noqa: E501
        :rtype: list[str]
        """
        return self._owner_ids

    @owner_ids.setter
    def owner_ids(self, owner_ids):
        """Sets the owner_ids of this CreateTask.

        An array of UUIDs for any members you want to add as Owners on this new Task.  # noqa: E501

        :param owner_ids: The owner_ids of this CreateTask.  # noqa: E501
        :type: list[str]
        """

        self._owner_ids = owner_ids

    @property
    def created_at(self):
        """Gets the created_at of this CreateTask.  # noqa: E501

        Defaults to the time/date the Task is created but can be set to reflect another creation time/date.  # noqa: E501

        :return: The created_at of this CreateTask.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this CreateTask.

        Defaults to the time/date the Task is created but can be set to reflect another creation time/date.  # noqa: E501

        :param created_at: The created_at of this CreateTask.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this CreateTask.  # noqa: E501

        Defaults to the time/date the Task is created in Shortcut but can be set to reflect another time/date.  # noqa: E501

        :return: The updated_at of this CreateTask.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this CreateTask.

        Defaults to the time/date the Task is created in Shortcut but can be set to reflect another time/date.  # noqa: E501

        :param updated_at: The updated_at of this CreateTask.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def external_id(self):
        """Gets the external_id of this CreateTask.  # noqa: E501

        This field can be set to another unique ID. In the case that the Task has been imported from another tool, the ID in the other tool can be indicated here.  # noqa: E501

        :return: The external_id of this CreateTask.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this CreateTask.

        This field can be set to another unique ID. In the case that the Task has been imported from another tool, the ID in the other tool can be indicated here.  # noqa: E501

        :param external_id: The external_id of this CreateTask.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateTask, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
