# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EntityTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_type': 'str',
        'id': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'name': 'str',
        'author_id': 'str',
        'last_used_at': 'datetime',
        'story_contents': 'StoryContents'
    }

    attribute_map = {
        'entity_type': 'entity_type',
        'id': 'id',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'name': 'name',
        'author_id': 'author_id',
        'last_used_at': 'last_used_at',
        'story_contents': 'story_contents'
    }

    def __init__(self, entity_type=None, id=None, created_at=None, updated_at=None, name=None, author_id=None, last_used_at=None, story_contents=None):  # noqa: E501
        """EntityTemplate - a model defined in Swagger"""  # noqa: E501
        self._entity_type = None
        self._id = None
        self._created_at = None
        self._updated_at = None
        self._name = None
        self._author_id = None
        self._last_used_at = None
        self._story_contents = None
        self.discriminator = None
        self.entity_type = entity_type
        self.id = id
        self.created_at = created_at
        self.updated_at = updated_at
        self.name = name
        self.author_id = author_id
        self.last_used_at = last_used_at
        self.story_contents = story_contents

    @property
    def entity_type(self):
        """Gets the entity_type of this EntityTemplate.  # noqa: E501

        A string description of this resource.  # noqa: E501

        :return: The entity_type of this EntityTemplate.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this EntityTemplate.

        A string description of this resource.  # noqa: E501

        :param entity_type: The entity_type of this EntityTemplate.  # noqa: E501
        :type: str
        """
        if entity_type is None:
            raise ValueError("Invalid value for `entity_type`, must not be `None`")  # noqa: E501

        self._entity_type = entity_type

    @property
    def id(self):
        """Gets the id of this EntityTemplate.  # noqa: E501

        The unique identifier for the entity template.  # noqa: E501

        :return: The id of this EntityTemplate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EntityTemplate.

        The unique identifier for the entity template.  # noqa: E501

        :param id: The id of this EntityTemplate.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this EntityTemplate.  # noqa: E501

        The time/date when the entity template was created.  # noqa: E501

        :return: The created_at of this EntityTemplate.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this EntityTemplate.

        The time/date when the entity template was created.  # noqa: E501

        :param created_at: The created_at of this EntityTemplate.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this EntityTemplate.  # noqa: E501

        The time/date when the entity template was last updated.  # noqa: E501

        :return: The updated_at of this EntityTemplate.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this EntityTemplate.

        The time/date when the entity template was last updated.  # noqa: E501

        :param updated_at: The updated_at of this EntityTemplate.  # noqa: E501
        :type: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def name(self):
        """Gets the name of this EntityTemplate.  # noqa: E501

        The template's name.  # noqa: E501

        :return: The name of this EntityTemplate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EntityTemplate.

        The template's name.  # noqa: E501

        :param name: The name of this EntityTemplate.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def author_id(self):
        """Gets the author_id of this EntityTemplate.  # noqa: E501

        The unique ID of the member who created the template.  # noqa: E501

        :return: The author_id of this EntityTemplate.  # noqa: E501
        :rtype: str
        """
        return self._author_id

    @author_id.setter
    def author_id(self, author_id):
        """Sets the author_id of this EntityTemplate.

        The unique ID of the member who created the template.  # noqa: E501

        :param author_id: The author_id of this EntityTemplate.  # noqa: E501
        :type: str
        """
        if author_id is None:
            raise ValueError("Invalid value for `author_id`, must not be `None`")  # noqa: E501

        self._author_id = author_id

    @property
    def last_used_at(self):
        """Gets the last_used_at of this EntityTemplate.  # noqa: E501

        The last time that someone created an entity using this template.  # noqa: E501

        :return: The last_used_at of this EntityTemplate.  # noqa: E501
        :rtype: datetime
        """
        return self._last_used_at

    @last_used_at.setter
    def last_used_at(self, last_used_at):
        """Sets the last_used_at of this EntityTemplate.

        The last time that someone created an entity using this template.  # noqa: E501

        :param last_used_at: The last_used_at of this EntityTemplate.  # noqa: E501
        :type: datetime
        """
        if last_used_at is None:
            raise ValueError("Invalid value for `last_used_at`, must not be `None`")  # noqa: E501

        self._last_used_at = last_used_at

    @property
    def story_contents(self):
        """Gets the story_contents of this EntityTemplate.  # noqa: E501


        :return: The story_contents of this EntityTemplate.  # noqa: E501
        :rtype: StoryContents
        """
        return self._story_contents

    @story_contents.setter
    def story_contents(self, story_contents):
        """Sets the story_contents of this EntityTemplate.


        :param story_contents: The story_contents of this EntityTemplate.  # noqa: E501
        :type: StoryContents
        """
        if story_contents is None:
            raise ValueError("Invalid value for `story_contents`, must not be `None`")  # noqa: E501

        self._story_contents = story_contents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EntityTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EntityTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
