# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetExternalLinkStoriesParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'external_link': 'str'
    }

    attribute_map = {
        'external_link': 'external_link'
    }

    def __init__(self, external_link=None):  # noqa: E501
        """GetExternalLinkStoriesParams - a model defined in Swagger"""  # noqa: E501
        self._external_link = None
        self.discriminator = None
        self.external_link = external_link

    @property
    def external_link(self):
        """Gets the external_link of this GetExternalLinkStoriesParams.  # noqa: E501

        The external link associated with one or more stories.  # noqa: E501

        :return: The external_link of this GetExternalLinkStoriesParams.  # noqa: E501
        :rtype: str
        """
        return self._external_link

    @external_link.setter
    def external_link(self, external_link):
        """Sets the external_link of this GetExternalLinkStoriesParams.

        The external link associated with one or more stories.  # noqa: E501

        :param external_link: The external_link of this GetExternalLinkStoriesParams.  # noqa: E501
        :type: str
        """
        if external_link is None:
            raise ValueError("Invalid value for `external_link`, must not be `None`")  # noqa: E501

        self._external_link = external_link

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetExternalLinkStoriesParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetExternalLinkStoriesParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
