# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HistoryActionTaskUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'entity_type': 'str',
        'action': 'str',
        'changes': 'HistoryChangesTask',
        'complete': 'bool',
        'description': 'str',
        'story_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'entity_type': 'entity_type',
        'action': 'action',
        'changes': 'changes',
        'complete': 'complete',
        'description': 'description',
        'story_id': 'story_id'
    }

    def __init__(self, id=None, entity_type=None, action=None, changes=None, complete=None, description=None, story_id=None):  # noqa: E501
        """HistoryActionTaskUpdate - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._entity_type = None
        self._action = None
        self._changes = None
        self._complete = None
        self._description = None
        self._story_id = None
        self.discriminator = None
        self.id = id
        self.entity_type = entity_type
        self.action = action
        self.changes = changes
        if complete is not None:
            self.complete = complete
        self.description = description
        self.story_id = story_id

    @property
    def id(self):
        """Gets the id of this HistoryActionTaskUpdate.  # noqa: E501

        The ID of the entity referenced.  # noqa: E501

        :return: The id of this HistoryActionTaskUpdate.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this HistoryActionTaskUpdate.

        The ID of the entity referenced.  # noqa: E501

        :param id: The id of this HistoryActionTaskUpdate.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def entity_type(self):
        """Gets the entity_type of this HistoryActionTaskUpdate.  # noqa: E501

        The type of entity referenced.  # noqa: E501

        :return: The entity_type of this HistoryActionTaskUpdate.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this HistoryActionTaskUpdate.

        The type of entity referenced.  # noqa: E501

        :param entity_type: The entity_type of this HistoryActionTaskUpdate.  # noqa: E501
        :type: str
        """
        if entity_type is None:
            raise ValueError("Invalid value for `entity_type`, must not be `None`")  # noqa: E501

        self._entity_type = entity_type

    @property
    def action(self):
        """Gets the action of this HistoryActionTaskUpdate.  # noqa: E501

        The action of the entity referenced.  # noqa: E501

        :return: The action of this HistoryActionTaskUpdate.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this HistoryActionTaskUpdate.

        The action of the entity referenced.  # noqa: E501

        :param action: The action of this HistoryActionTaskUpdate.  # noqa: E501
        :type: str
        """
        if action is None:
            raise ValueError("Invalid value for `action`, must not be `None`")  # noqa: E501
        allowed_values = ["update"]  # noqa: E501
        if action not in allowed_values:
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"  # noqa: E501
                .format(action, allowed_values)
            )

        self._action = action

    @property
    def changes(self):
        """Gets the changes of this HistoryActionTaskUpdate.  # noqa: E501


        :return: The changes of this HistoryActionTaskUpdate.  # noqa: E501
        :rtype: HistoryChangesTask
        """
        return self._changes

    @changes.setter
    def changes(self, changes):
        """Sets the changes of this HistoryActionTaskUpdate.


        :param changes: The changes of this HistoryActionTaskUpdate.  # noqa: E501
        :type: HistoryChangesTask
        """
        if changes is None:
            raise ValueError("Invalid value for `changes`, must not be `None`")  # noqa: E501

        self._changes = changes

    @property
    def complete(self):
        """Gets the complete of this HistoryActionTaskUpdate.  # noqa: E501

        Whether or not the Task is complete.  # noqa: E501

        :return: The complete of this HistoryActionTaskUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._complete

    @complete.setter
    def complete(self, complete):
        """Sets the complete of this HistoryActionTaskUpdate.

        Whether or not the Task is complete.  # noqa: E501

        :param complete: The complete of this HistoryActionTaskUpdate.  # noqa: E501
        :type: bool
        """

        self._complete = complete

    @property
    def description(self):
        """Gets the description of this HistoryActionTaskUpdate.  # noqa: E501

        The description of the Task.  # noqa: E501

        :return: The description of this HistoryActionTaskUpdate.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this HistoryActionTaskUpdate.

        The description of the Task.  # noqa: E501

        :param description: The description of this HistoryActionTaskUpdate.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def story_id(self):
        """Gets the story_id of this HistoryActionTaskUpdate.  # noqa: E501

        The Story ID that contains the Task.  # noqa: E501

        :return: The story_id of this HistoryActionTaskUpdate.  # noqa: E501
        :rtype: int
        """
        return self._story_id

    @story_id.setter
    def story_id(self, story_id):
        """Sets the story_id of this HistoryActionTaskUpdate.

        The Story ID that contains the Task.  # noqa: E501

        :param story_id: The story_id of this HistoryActionTaskUpdate.  # noqa: E501
        :type: int
        """
        if story_id is None:
            raise ValueError("Invalid value for `story_id`, must not be `None`")  # noqa: E501

        self._story_id = story_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoryActionTaskUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoryActionTaskUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
