# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PullRequestLabel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_type': 'str',
        'id': 'int',
        'color': 'str',
        'description': 'str',
        'name': 'str'
    }

    attribute_map = {
        'entity_type': 'entity_type',
        'id': 'id',
        'color': 'color',
        'description': 'description',
        'name': 'name'
    }

    def __init__(self, entity_type=None, id=None, color=None, description=None, name=None):  # noqa: E501
        """PullRequestLabel - a model defined in Swagger"""  # noqa: E501
        self._entity_type = None
        self._id = None
        self._color = None
        self._description = None
        self._name = None
        self.discriminator = None
        self.entity_type = entity_type
        self.id = id
        self.color = color
        if description is not None:
            self.description = description
        self.name = name

    @property
    def entity_type(self):
        """Gets the entity_type of this PullRequestLabel.  # noqa: E501

        A string description of this resource.  # noqa: E501

        :return: The entity_type of this PullRequestLabel.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this PullRequestLabel.

        A string description of this resource.  # noqa: E501

        :param entity_type: The entity_type of this PullRequestLabel.  # noqa: E501
        :type: str
        """
        if entity_type is None:
            raise ValueError("Invalid value for `entity_type`, must not be `None`")  # noqa: E501

        self._entity_type = entity_type

    @property
    def id(self):
        """Gets the id of this PullRequestLabel.  # noqa: E501

        The unique ID of the VCS Label.  # noqa: E501

        :return: The id of this PullRequestLabel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PullRequestLabel.

        The unique ID of the VCS Label.  # noqa: E501

        :param id: The id of this PullRequestLabel.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def color(self):
        """Gets the color of this PullRequestLabel.  # noqa: E501

        The color of the VCS label.  # noqa: E501

        :return: The color of this PullRequestLabel.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this PullRequestLabel.

        The color of the VCS label.  # noqa: E501

        :param color: The color of this PullRequestLabel.  # noqa: E501
        :type: str
        """
        if color is None:
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501

        self._color = color

    @property
    def description(self):
        """Gets the description of this PullRequestLabel.  # noqa: E501

        The description of the VCS label.  # noqa: E501

        :return: The description of this PullRequestLabel.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PullRequestLabel.

        The description of the VCS label.  # noqa: E501

        :param description: The description of this PullRequestLabel.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this PullRequestLabel.  # noqa: E501

        The name of the VCS label.  # noqa: E501

        :return: The name of this PullRequestLabel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PullRequestLabel.

        The name of the VCS label.  # noqa: E501

        :param name: The name of this PullRequestLabel.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PullRequestLabel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PullRequestLabel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
