# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StoryHistoryChangeAddsRemovesUuid(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'adds': 'list[str]',
        'removes': 'list[str]'
    }

    attribute_map = {
        'adds': 'adds',
        'removes': 'removes'
    }

    def __init__(self, adds=None, removes=None):  # noqa: E501
        """StoryHistoryChangeAddsRemovesUuid - a model defined in Swagger"""  # noqa: E501
        self._adds = None
        self._removes = None
        self.discriminator = None
        if adds is not None:
            self.adds = adds
        if removes is not None:
            self.removes = removes

    @property
    def adds(self):
        """Gets the adds of this StoryHistoryChangeAddsRemovesUuid.  # noqa: E501

        The values that have been added.  # noqa: E501

        :return: The adds of this StoryHistoryChangeAddsRemovesUuid.  # noqa: E501
        :rtype: list[str]
        """
        return self._adds

    @adds.setter
    def adds(self, adds):
        """Sets the adds of this StoryHistoryChangeAddsRemovesUuid.

        The values that have been added.  # noqa: E501

        :param adds: The adds of this StoryHistoryChangeAddsRemovesUuid.  # noqa: E501
        :type: list[str]
        """

        self._adds = adds

    @property
    def removes(self):
        """Gets the removes of this StoryHistoryChangeAddsRemovesUuid.  # noqa: E501

        The values that have been removed  # noqa: E501

        :return: The removes of this StoryHistoryChangeAddsRemovesUuid.  # noqa: E501
        :rtype: list[str]
        """
        return self._removes

    @removes.setter
    def removes(self, removes):
        """Sets the removes of this StoryHistoryChangeAddsRemovesUuid.

        The values that have been removed  # noqa: E501

        :param removes: The removes of this StoryHistoryChangeAddsRemovesUuid.  # noqa: E501
        :type: list[str]
        """

        self._removes = removes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StoryHistoryChangeAddsRemovesUuid, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StoryHistoryChangeAddsRemovesUuid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
