# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StoryCustomField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field_id': 'str',
        'value_id': 'str',
        'value': 'str'
    }

    attribute_map = {
        'field_id': 'field_id',
        'value_id': 'value_id',
        'value': 'value'
    }

    def __init__(self, field_id=None, value_id=None, value=None):  # noqa: E501
        """StoryCustomField - a model defined in Swagger"""  # noqa: E501
        self._field_id = None
        self._value_id = None
        self._value = None
        self.discriminator = None
        self.field_id = field_id
        self.value_id = value_id
        self.value = value

    @property
    def field_id(self):
        """Gets the field_id of this StoryCustomField.  # noqa: E501

        The unique public ID for a CustomField.  # noqa: E501

        :return: The field_id of this StoryCustomField.  # noqa: E501
        :rtype: str
        """
        return self._field_id

    @field_id.setter
    def field_id(self, field_id):
        """Sets the field_id of this StoryCustomField.

        The unique public ID for a CustomField.  # noqa: E501

        :param field_id: The field_id of this StoryCustomField.  # noqa: E501
        :type: str
        """
        if field_id is None:
            raise ValueError("Invalid value for `field_id`, must not be `None`")  # noqa: E501

        self._field_id = field_id

    @property
    def value_id(self):
        """Gets the value_id of this StoryCustomField.  # noqa: E501

        The unique public ID for a CustomFieldEnumValue.  # noqa: E501

        :return: The value_id of this StoryCustomField.  # noqa: E501
        :rtype: str
        """
        return self._value_id

    @value_id.setter
    def value_id(self, value_id):
        """Sets the value_id of this StoryCustomField.

        The unique public ID for a CustomFieldEnumValue.  # noqa: E501

        :param value_id: The value_id of this StoryCustomField.  # noqa: E501
        :type: str
        """
        if value_id is None:
            raise ValueError("Invalid value for `value_id`, must not be `None`")  # noqa: E501

        self._value_id = value_id

    @property
    def value(self):
        """Gets the value of this StoryCustomField.  # noqa: E501

        A string representation of the value, if applicable.  # noqa: E501

        :return: The value of this StoryCustomField.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this StoryCustomField.

        A string representation of the value, if applicable.  # noqa: E501

        :param value: The value of this StoryCustomField.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StoryCustomField, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StoryCustomField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
