# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StoryReaction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'emoji': 'str',
        'permission_ids': 'list[str]'
    }

    attribute_map = {
        'emoji': 'emoji',
        'permission_ids': 'permission_ids'
    }

    def __init__(self, emoji=None, permission_ids=None):  # noqa: E501
        """StoryReaction - a model defined in Swagger"""  # noqa: E501
        self._emoji = None
        self._permission_ids = None
        self.discriminator = None
        self.emoji = emoji
        self.permission_ids = permission_ids

    @property
    def emoji(self):
        """Gets the emoji of this StoryReaction.  # noqa: E501

        Emoji text of the reaction.  # noqa: E501

        :return: The emoji of this StoryReaction.  # noqa: E501
        :rtype: str
        """
        return self._emoji

    @emoji.setter
    def emoji(self, emoji):
        """Sets the emoji of this StoryReaction.

        Emoji text of the reaction.  # noqa: E501

        :param emoji: The emoji of this StoryReaction.  # noqa: E501
        :type: str
        """
        if emoji is None:
            raise ValueError("Invalid value for `emoji`, must not be `None`")  # noqa: E501

        self._emoji = emoji

    @property
    def permission_ids(self):
        """Gets the permission_ids of this StoryReaction.  # noqa: E501

        Permissions who have reacted with this.  # noqa: E501

        :return: The permission_ids of this StoryReaction.  # noqa: E501
        :rtype: list[str]
        """
        return self._permission_ids

    @permission_ids.setter
    def permission_ids(self, permission_ids):
        """Sets the permission_ids of this StoryReaction.

        Permissions who have reacted with this.  # noqa: E501

        :param permission_ids: The permission_ids of this StoryReaction.  # noqa: E501
        :type: list[str]
        """
        if permission_ids is None:
            raise ValueError("Invalid value for `permission_ids`, must not be `None`")  # noqa: E501

        self._permission_ids = permission_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StoryReaction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StoryReaction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
