# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateLabel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'color': 'str',
        'archived': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'color': 'color',
        'archived': 'archived'
    }

    def __init__(self, name=None, description=None, color=None, archived=None):  # noqa: E501
        """UpdateLabel - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._color = None
        self._archived = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if color is not None:
            self.color = color
        if archived is not None:
            self.archived = archived

    @property
    def name(self):
        """Gets the name of this UpdateLabel.  # noqa: E501

        The new name of the label.  # noqa: E501

        :return: The name of this UpdateLabel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UpdateLabel.

        The new name of the label.  # noqa: E501

        :param name: The name of this UpdateLabel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this UpdateLabel.  # noqa: E501

        The new description of the label.  # noqa: E501

        :return: The description of this UpdateLabel.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateLabel.

        The new description of the label.  # noqa: E501

        :param description: The description of this UpdateLabel.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def color(self):
        """Gets the color of this UpdateLabel.  # noqa: E501

        The hex color to be displayed with the Label (for example, \"#ff0000\").  # noqa: E501

        :return: The color of this UpdateLabel.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this UpdateLabel.

        The hex color to be displayed with the Label (for example, \"#ff0000\").  # noqa: E501

        :param color: The color of this UpdateLabel.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def archived(self):
        """Gets the archived of this UpdateLabel.  # noqa: E501

        A true/false boolean indicating if the Label has been archived.  # noqa: E501

        :return: The archived of this UpdateLabel.  # noqa: E501
        :rtype: bool
        """
        return self._archived

    @archived.setter
    def archived(self, archived):
        """Sets the archived of this UpdateLabel.

        A true/false boolean indicating if the Label has been archived.  # noqa: E501

        :param archived: The archived of this UpdateLabel.  # noqa: E501
        :type: bool
        """

        self._archived = archived

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateLabel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateLabel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
