# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateTask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'owner_ids': 'list[str]',
        'complete': 'bool',
        'before_id': 'int',
        'after_id': 'int'
    }

    attribute_map = {
        'description': 'description',
        'owner_ids': 'owner_ids',
        'complete': 'complete',
        'before_id': 'before_id',
        'after_id': 'after_id'
    }

    def __init__(self, description=None, owner_ids=None, complete=None, before_id=None, after_id=None):  # noqa: E501
        """UpdateTask - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._owner_ids = None
        self._complete = None
        self._before_id = None
        self._after_id = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if owner_ids is not None:
            self.owner_ids = owner_ids
        if complete is not None:
            self.complete = complete
        if before_id is not None:
            self.before_id = before_id
        if after_id is not None:
            self.after_id = after_id

    @property
    def description(self):
        """Gets the description of this UpdateTask.  # noqa: E501

        The Task's description.  # noqa: E501

        :return: The description of this UpdateTask.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateTask.

        The Task's description.  # noqa: E501

        :param description: The description of this UpdateTask.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def owner_ids(self):
        """Gets the owner_ids of this UpdateTask.  # noqa: E501

        An array of UUIDs of the owners of this story.  # noqa: E501

        :return: The owner_ids of this UpdateTask.  # noqa: E501
        :rtype: list[str]
        """
        return self._owner_ids

    @owner_ids.setter
    def owner_ids(self, owner_ids):
        """Sets the owner_ids of this UpdateTask.

        An array of UUIDs of the owners of this story.  # noqa: E501

        :param owner_ids: The owner_ids of this UpdateTask.  # noqa: E501
        :type: list[str]
        """

        self._owner_ids = owner_ids

    @property
    def complete(self):
        """Gets the complete of this UpdateTask.  # noqa: E501

        A true/false boolean indicating whether the task is complete.  # noqa: E501

        :return: The complete of this UpdateTask.  # noqa: E501
        :rtype: bool
        """
        return self._complete

    @complete.setter
    def complete(self, complete):
        """Sets the complete of this UpdateTask.

        A true/false boolean indicating whether the task is complete.  # noqa: E501

        :param complete: The complete of this UpdateTask.  # noqa: E501
        :type: bool
        """

        self._complete = complete

    @property
    def before_id(self):
        """Gets the before_id of this UpdateTask.  # noqa: E501

        Move task before this task ID.  # noqa: E501

        :return: The before_id of this UpdateTask.  # noqa: E501
        :rtype: int
        """
        return self._before_id

    @before_id.setter
    def before_id(self, before_id):
        """Sets the before_id of this UpdateTask.

        Move task before this task ID.  # noqa: E501

        :param before_id: The before_id of this UpdateTask.  # noqa: E501
        :type: int
        """

        self._before_id = before_id

    @property
    def after_id(self):
        """Gets the after_id of this UpdateTask.  # noqa: E501

        Move task after this task ID.  # noqa: E501

        :return: The after_id of this UpdateTask.  # noqa: E501
        :rtype: int
        """
        return self._after_id

    @after_id.setter
    def after_id(self, after_id):
        """Sets the after_id of this UpdateTask.

        Move task after this task ID.  # noqa: E501

        :param after_id: The after_id of this UpdateTask.  # noqa: E501
        :type: int
        """

        self._after_id = after_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateTask, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
